package com.threads.basics;

public class Greetings {
   public String sayHello(String name){
        String result = null;
        try {
            System.out.println("hi "+name);
            Thread.sleep(1000);
            result = "Great day "+name;
        }catch (InterruptedException e){
            //TODO Autogenerated catch block
            e.printStackTrace();
        }
        return result;
    }
}
